language: clojure
services:
 - xvfb
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libgfortran3
install: lein modules install
before_script:
  - "export DISPLAY=:99.0"
script: lein modules test
